### ISSUE TITLE
struct.error: unpack_from requires a buffer of at least 4 bytes

### ISSUE THREAD

**Issue by demux** [mideind/ReynirPackage#16]
Steps:
- `apt install git-lfs`
- `git clone https://github.com/mideind/ReynirPackage`
- `cd ReynirPackage`
- `python setup.py develop`
- `pip install pytest`
- `python -m pytest`

Results in the following error:

![Selection_051](https://user-images.githubusercontent.com/202432/71585141-75413b80-2b0d-11ea-9f68-b38d8091522d.png)

![image](https://user-images.githubusercontent.com/202432/71585092-52af2280-2b0d-11ea-818c-d941f2fd9631.png)

**Comment by demux** [comment]
@vthorsteinsson: Any idea what's happening here? Am I doing something wrong?

**Comment by vthorsteinsson** [comment]
Check `ReynirPackage/src/reynir/resources/ord.compressed`; this file should be ~75M in size. If it is ~100 bytes, `git-lfs` didn't pull it from the remote repo. You are probably missing the `git lfs install` command, as per these instructions: https://git-lfs.github.com/
